/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import boundaryclasses.DbManager;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JPanel;
import javax.swing.JTextField;
import model.Country;
import model.Coviddata;

public class DataMapView extends javax.swing.JPanel {

    public DataMapView() {
        initComponents();
    }
    //Έχουν προστεθεί getters για να διαχειρίζεται το GUI ο Presenter
    public JButton getBackToOptionsButton() {
        return backToOptionsButton;
    }

    public JComboBox<Country> getCountriesComboBox() {
        return countriesComboBox;
    }

    public JList<Country> getCountriesJList() {
        return countriesJList;
    }

    public JButton getFromButton() {
        return fromButton;
    }

    public JTextField getFromTextField() {
        return fromTextField;
    }

    public List<Country> getMainCountryList() {
        return mainCountryList;
    }

    public List<Country> getRestCountriesList() {
        return restCountriesList;
    }

    public JButton getToButton() {
        return toButton;
    }

    public JTextField getToTextField() {
        return toTextField;
    }

    public JButton getShowMapButton() {
        return showMapButton;
    }

    public JPanel getMapPanel() {
        return MapPanel;
    }

    public JLabel getInfoTextLabel() {
        return infoTextLabel;
    }

    public JLabel getLoadingLabel() {
        return loadingLabel;
    }

    public JLabel getDateErrorLabel() {
        return dateErrorLabel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        em = DbManager.getEm();
        countryListQuery = java.beans.Beans.isDesignTime() ? null : em.createNamedQuery("Country.findByData", Country.class);
        mainCountryList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : org.jdesktop.observablecollections.ObservableCollections.observableList(countryListQuery.getResultList());
        restCountriesList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : new ArrayList<Country>();
        backToOptionsButton = new javax.swing.JButton();
        title = new javax.swing.JLabel();
        MapPanel = new javax.swing.JPanel();
        infoTextLabel = new javax.swing.JLabel();
        loadingLabel = new javax.swing.JLabel();
        countriesComboBox = new javax.swing.JComboBox<Country>(mainCountryList.toArray(new Country[0]));
        basicCountryLabel = new javax.swing.JLabel();
        countriesLabel = new javax.swing.JLabel();
        fromLabel = new javax.swing.JLabel();
        toLabel = new javax.swing.JLabel();
        fromTextField = new javax.swing.JTextField();
        toTextField = new javax.swing.JTextField();
        fromButton = new javax.swing.JButton();
        toButton = new javax.swing.JButton();
        showMapButton = new javax.swing.JButton();
        dateErrorLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        countriesJList = new javax.swing.JList<>();

        em.clear();

        for(Country c: mainCountryList) {
            if(c.getCoviddataList() == null || c.getCoviddataList().isEmpty())
            c.setCoviddataList(em.createNamedQuery("Coviddata.findByCountry", Coviddata.class).setParameter("coutryname", c.getName()).getResultList());
        }
        Collections.sort(mainCountryList);

        restCountriesList.addAll(mainCountryList);

        setPreferredSize(new java.awt.Dimension(840, 640));

        backToOptionsButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/menu.png"))); // NOI18N
        backToOptionsButton.setText("<html><p >Κεντρικό</p><p style=\"text-align:center\">Μενού</p></html>");
        backToOptionsButton.setMaximumSize(new java.awt.Dimension(114, 56));
        backToOptionsButton.setPreferredSize(new java.awt.Dimension(114, 56));

        title.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        title.setText("Προβολή δεδομένων σε χάρτη");

        MapPanel.setMaximumSize(new java.awt.Dimension(834, 441));
        MapPanel.setMinimumSize(new java.awt.Dimension(834, 441));
        MapPanel.setName(""); // NOI18N
        MapPanel.setPreferredSize(new java.awt.Dimension(834, 441));
        MapPanel.setLayout(new java.awt.GridLayout(0, 1));

        infoTextLabel.setText("Επιλέξτε μια βασική χώρα και τις υπόλοιπες χώρες που επιθυμείτε. Ο χάρτης θα εστιάσει στην βασική χώρα");
        infoTextLabel.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        MapPanel.add(infoTextLabel);
        infoTextLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        loadingLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loadingLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ajax-loader.gif"))); // NOI18N
        loadingLabel.setPreferredSize(new java.awt.Dimension(800, 100));
        MapPanel.add(loadingLabel);
        loadingLabel.setVisible(false);

        countriesComboBox.setSelectedIndex(-1);

        basicCountryLabel.setText("Επιλέξτε Βασική Χώρα");

        countriesLabel.setText("Επιλέξτε τις υπόλοιπες χώρες");

        fromLabel.setText("Από:");

        toLabel.setText("Έως:");

        fromTextField.setEditable(false);

        toTextField.setEditable(false);

        fromButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/calendar.png"))); // NOI18N
        fromButton.setEnabled(false);
        fromButton.setPreferredSize(new java.awt.Dimension(29, 29));

        toButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/calendar.png"))); // NOI18N
        toButton.setEnabled(false);
        toButton.setPreferredSize(new java.awt.Dimension(29, 29));

        showMapButton.setText("Προβολή χάρτη");
        showMapButton.setEnabled(false);

        dateErrorLabel.setText("<html><span style=\"color:red\">Η ημ/νία έως πρέπει να είναι μετά την ημ/νία από</span></html>");

        org.jdesktop.swingbinding.JListBinding jListBinding = org.jdesktop.swingbinding.SwingBindings.createJListBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, restCountriesList, countriesJList);
        jListBinding.setDetailBinding(org.jdesktop.beansbinding.ELProperty.create("${name}"));
        bindingGroup.addBinding(jListBinding);

        jScrollPane2.setViewportView(countriesJList);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(countriesComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(279, 279, 279)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(fromLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(fromTextField))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(toLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(toTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(fromButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(toButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(showMapButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(256, 256, 256)
                                .addComponent(dateErrorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(title)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(backToOptionsButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(basicCountryLabel)
                                .addGap(123, 123, 123)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(countriesLabel))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addComponent(MapPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backToOptionsButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(title))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(basicCountryLabel)
                    .addComponent(countriesLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(countriesComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(fromLabel)
                                    .addComponent(fromTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fromButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(toLabel)
                                    .addComponent(toTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(toButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(showMapButton, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dateErrorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(21, 21, 21)
                .addComponent(MapPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        dateErrorLabel.setVisible(false);

        bindingGroup.bind();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MapPanel;
    private javax.swing.JButton backToOptionsButton;
    private javax.swing.JLabel basicCountryLabel;
    private javax.swing.JComboBox<Country> countriesComboBox;
    private javax.swing.JList<Country> countriesJList;
    private javax.swing.JLabel countriesLabel;
    private javax.persistence.Query countryListQuery;
    private javax.swing.JLabel dateErrorLabel;
    private javax.persistence.EntityManager em;
    private javax.swing.JButton fromButton;
    private javax.swing.JLabel fromLabel;
    private javax.swing.JTextField fromTextField;
    private javax.swing.JLabel infoTextLabel;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel loadingLabel;
    private java.util.List<Country> mainCountryList;
    private java.util.List<Country> restCountriesList;
    private javax.swing.JButton showMapButton;
    private javax.swing.JLabel title;
    private javax.swing.JButton toButton;
    private javax.swing.JLabel toLabel;
    private javax.swing.JTextField toTextField;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
