/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import javax.swing.JButton;
import javax.swing.JLabel;

/**
 *
 * 
 */
public class OptionsView extends javax.swing.JPanel {

    /**
     * Creates new form OptionsView
     */
    public OptionsView() {
        initComponents();
    }
    //Έχουν προστεθεί getters για να διαχειρίζεται το GUI ο Presenter
    public JButton getCountryButton() {
        return countryButton;
    }

    public JButton getDataButton() {
        return dataButton;
    }

    public JButton getExitButton() {
        return exitButton;
    }

    public JButton getMapButton() {
        return mapButton;
    }

    public JLabel getInfoLabel() {
        return infoLabel;
    }

    public JLabel getIconLabel() {
        return iconLabel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dataButton = new javax.swing.JButton();
        countryButton = new javax.swing.JButton();
        mapButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();
        infoLabel = new javax.swing.JLabel();
        iconLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        title = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(840, 640));

        dataButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/database.png"))); // NOI18N
        dataButton.setText("<html>\n   <p style=\"text-align:center\">Διαχείριση δεδομένων</p>\n   <p style=\"text-align:center\">Covid19</p>\n</html>");
        dataButton.setMaximumSize(new java.awt.Dimension(114, 56));
        dataButton.setMinimumSize(new java.awt.Dimension(114, 56));
        dataButton.setPreferredSize(new java.awt.Dimension(114, 56));

        countryButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/country.png"))); // NOI18N
        countryButton.setText("<html>Προβολή δεδομένων Covid19 ανά χώρα</html>");
        countryButton.setMaximumSize(new java.awt.Dimension(114, 90));
        countryButton.setMinimumSize(new java.awt.Dimension(114, 90));
        countryButton.setPreferredSize(new java.awt.Dimension(114, 90));

        mapButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/map.png"))); // NOI18N
        mapButton.setText("<html>Προβολή δεδομένων Covid19 σε χάρτη</html>");

        exitButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/exit.png"))); // NOI18N
        exitButton.setText("Έξοδος");
        exitButton.setPreferredSize(new java.awt.Dimension(114, 56));

        infoLabel.setForeground(java.awt.Color.blue);
        infoLabel.setText("Σύνδεση με τη βάση δεδομένων, παρακαλώ περιμένετε...");
        infoLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        iconLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ajax-loader1.gif"))); // NOI18N

        title.setFont(new java.awt.Font("sansserif", 1, 48)); // NOI18N
        title.setText("Covid data App");

        jLabel1.setText("<html>\n   <h3>Επιλογές διαχείρισης βάσης δεδομένων</h3>\n   <p>-Εισαγωγή δεδομένων από το ίντερνετ</p>\n   <p>-Προβολή των αποθηκευμένων δεδομένων στην βάση δεδομένων,</p>\n   <p>-Διαγραφή δεδομένων</p>\n</html>");

        jLabel2.setText("<html>\n   <h3>Επιλογές προβολής δεδομένων</h3>\n   <p>-Προβολή δεδομένων ανά χώρα σε πίνακα</p>\n   <p>-Προβολή δεδομένων ανά χώρα σε γράφημα</p>\n   <p>-Προβολή δεδομένων ανά χώρα σε χάρτη</p>\n   <p>-Διαγραφή δεδομένων</p>\n</html>");

        jLabel3.setText("<html>    \n    <h3>Επιλογές προβολής δεδομένων σε χάρτη</h3>\n    <p>-Προβολή δεδομένων ανά χώρα σε χάρτη</p>\n    <p>-Δυνατότητα πολλαπλής επιλογής χωρών και προβολή σε χάρτη</p>\n </html>");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(iconLabel)
                .addGap(406, 406, 406))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(infoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(title)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(dataButton, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE)
                                    .addComponent(mapButton, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE)
                                    .addComponent(countryButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 198, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(title)))
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                    .addComponent(dataButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(countryButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(mapButton, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                    .addComponent(jLabel3))
                .addGap(50, 50, 50)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(infoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(iconLabel)
                .addGap(22, 22, 22))
        );

        infoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton countryButton;
    private javax.swing.JButton dataButton;
    private javax.swing.JButton exitButton;
    private javax.swing.JLabel iconLabel;
    private javax.swing.JLabel infoLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton mapButton;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
